In [5]:
   """ Resize the notbook to full width, to fit more code and images """
   from IPython.core.display import display, HTML
   display(HTML("<style>.container { width:100% !important; }</style>"))
   """ some basic packages and settings to show images inline """
   import numpy as np
   import importlib
   %matplotlib inline
   import matplotlib.pyplot as plt
   """ automatically reload included modules (need to run import command to trigger reloading) """
   %load_ext autoreload
   %autoreload 2
   """ Controls for figure sizes to change """
   plt.rcParams['figure.dpi'] = 200
   plt.rcParams['figure.figsize'] = [16, 8]
   plt.rcParams.update({'errorbar.capsize': 1})



The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [2]:
from template import *


Test of Linear layer

In [3]:
lin = HiddenLinearLayer()

In [36]:
x = np.arange()
lin.forward()

[0.5 0.5]


array([[-0.50432629, -0.18064884],
       [-0.48656582, -0.43099459],
       [-0.46643994, -0.53938273],
       [-0.37462169,  0.04571647],
       [-0.50275226, -0.0866657 ]])

[[-1.00865258 -0.36129768]
 [-0.97313164 -0.86198919]
 [-0.93287988 -1.07876546]
 [-0.74924338  0.09143294]
 [-1.00550452 -0.17333141]]


array([[0.        , 0.        ],
       [0.        , 0.        ],
       [0.        , 0.        ],
       [0.        , 0.09143294],
       [0.        , 0.        ]])

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 0]])

array([[ 0.12312505, -1.36959979],
       [-0.66741825,  0.45771649],
       [-1.46212022,  0.26358548],
       [ 0.80409543,  0.93496704],
       [ 0.25647913, -0.22918808]])

array([[ 0.        , -0.        ],
       [-0.        ,  0.        ],
       [-0.        ,  0.        ],
       [ 0.        ,  0.93496704],
       [ 0.        , -0.        ]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [92]:
x[0:1,:]

array([[-0.97971269,  0.40813205]])

array([[ 1.46907962,  0.89749898,  0.32591834, -0.2456623 , -0.81724293]])

array([[-0.97971269,  0.40813205],
       [ 0.92675003,  1.96362569],
       [-2.49523212, -1.0864822 ],
       [ 1.08514067,  0.30780262],
       [ 0.4825422 ,  1.52691122],
       [-0.34395061, -1.33802268],
       [ 0.26525724, -0.84184335]])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1 2]
 [3 4]]


array([[19, 23, 27, 31, 35],
       [26, 32, 38, 44, 50]])

array([ 2, -3])